##
# @file
# stylelint configuration.
#
# @see https://stylelint.io/user-guide/configure

# Extends Drupal default stylelint settings.
extends: stylelint-config-drupal

plugins:
  - stylelint-scss

rules:
  at-rule-empty-line-before:
    - always
    - ignore:
      - after-comment
      - blockless-after-same-name-blockless
      - first-nested
      - inside-block
  # scss/at-rule-no-unknown を利用するため無効化
  at-rule-no-unknown: null
  comment-empty-line-before: always
  font-family-no-missing-generic-family-keyword:
    - true
    - ignoreFontFamilies: ["Material Icons", "FontAwesome"]
  max-nesting-depth: 3
  # Drupal コアで設定される no-browser-hacks は SCSS の変数まで対象となってしまうため
  # 無効にする
  plugin/no-browser-hacks: null
  scss/at-rule-no-unknown: true
  scss/dollar-variable-colon-space-after: always
  scss/dollar-variable-colon-space-before: never
  scss/at-import-partial-extension: never
  scss/at-mixin-parentheses-space-before: never
  scss/no-duplicate-mixins: true
