language: php
php:
  - 5.5
  - 5.6
  
sudo: false

before_install:
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update
  - composer --version

install:
  - composer install -vvv

script:
  # Test stable release
  - cd $TRAVIS_BUILD_DIR/web
  - ./../vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite
  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
  - ./../vendor/bin/phpunit -c core --exclude-group Composer
  
  # Test dev release
  - cd $TRAVIS_BUILD_DIR
  - composer require -vvv --no-update drupal/core:8.0.x-dev 
  - composer update -vvv
  - cd $TRAVIS_BUILD_DIR/web
  - ./../vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite
  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
  - ./../vendor/bin/phpunit -c core --exclude-group Composer
