minimum_single: 10
minimum_multiple: 0
disable_search_threshold: 0
minimum_width: 0
jquery_selector: 'select:visible'
search_contains: true
disable_search: false
allow_single_deselect: true
placeholder_text_multiple: 'Choose some options'
placeholder_text_single: 'Choose an option'
no_results_text: 'No results match'
disabled_themes: {  }
chosen_include: 0
